# Generated by Django 4.2 on 2026-01-19 05:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='大学名または高校名', max_length=200, verbose_name='学校名')),
                ('name_kana', models.CharField(blank=True, help_text='検索用のかな表記', max_length=200, verbose_name='学校名（かな）')),
                ('school_type', models.CharField(choices=[('university', '大学'), ('high_school', '高校')], default='university', max_length=20, verbose_name='学校種別')),
                ('official_url', models.URLField(blank=True, verbose_name='公式サイトURL')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '学校',
                'verbose_name_plural': '学校一覧',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='SearchHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.CharField(max_length=200, verbose_name='検索クエリ')),
                ('filters', models.JSONField(default=dict, help_text='年度、科目などの絞り込み条件をJSON形式で保存', verbose_name='フィルター条件')),
                ('searched_at', models.DateTimeField(auto_now_add=True, verbose_name='検索日時')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_history', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': '検索履歴',
                'verbose_name_plural': '検索履歴一覧',
                'ordering': ['-searched_at'],
            },
        ),
        migrations.CreateModel(
            name='Exam',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(help_text='実施年度（例: 2024）', verbose_name='年度')),
                ('subject', models.CharField(choices=[('japanese', '国語'), ('math', '数学'), ('english', '英語'), ('science', '理科'), ('social', '社会'), ('physics', '物理'), ('chemistry', '化学'), ('biology', '生物'), ('geography', '地理'), ('history', '歴史'), ('other', 'その他')], max_length=50, verbose_name='科目')),
                ('exam_type', models.CharField(default='一般入試', help_text='例: 一般入試、推薦入試、共通テスト', max_length=50, verbose_name='試験種別')),
                ('problem_url', models.URLField(blank=True, help_text='大学公式または信頼できるソースの問題PDFリンク', verbose_name='問題PDF URL')),
                ('description', models.TextField(blank=True, help_text='問題の概要や特記事項', verbose_name='説明')),
                ('source_type', models.CharField(choices=[('official', '大学公式'), ('yobi_school', '予備校'), ('archive', 'アーカイブサイト'), ('other', 'その他')], default='official', max_length=50, verbose_name='ソース種別')),
                ('scraped_at', models.DateTimeField(blank=True, help_text='データを取得・確認した日時', null=True, verbose_name='取得日時')),
                ('is_verified', models.BooleanField(default=False, help_text='リンク切れチェック済み', verbose_name='検証済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('university', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exams', to='exams.university', verbose_name='学校')),
            ],
            options={
                'verbose_name': '過去問',
                'verbose_name_plural': '過去問一覧',
                'ordering': ['-year', 'university__name', 'subject'],
                'unique_together': {('university', 'year', 'subject', 'exam_type')},
            },
        ),
        migrations.CreateModel(
            name='AnswerSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider_name', models.CharField(help_text='例: 河合塾、駿台予備校、東進ハイスクール', max_length=100, verbose_name='提供元名')),
                ('answer_url', models.URLField(help_text='解答・解説ページへのリンク', verbose_name='解答URL')),
                ('has_detailed_explanation', models.BooleanField(default=False, help_text='詳しい解説が含まれているか', verbose_name='詳細解説あり')),
                ('has_video_explanation', models.BooleanField(default=False, verbose_name='動画解説あり')),
                ('reliability_score', models.IntegerField(default=5, help_text='1-10の範囲で評価（10が最高）', verbose_name='信頼度スコア')),
                ('notes', models.TextField(blank=True, help_text='解答の特徴や注意事項', verbose_name='備考')),
                ('last_checked_at', models.DateTimeField(blank=True, help_text='リンクが有効であることを最後に確認した日時', null=True, verbose_name='最終確認日時')),
                ('is_active', models.BooleanField(default=True, help_text='リンク切れの場合はFalseに設定', verbose_name='有効')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='登録日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answer_sources', to='exams.exam', verbose_name='過去問')),
            ],
            options={
                'verbose_name': '解答ソース',
                'verbose_name_plural': '解答ソース一覧',
                'ordering': ['-reliability_score', 'provider_name'],
            },
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='お気に入り登録日時')),
                ('note', models.TextField(blank=True, help_text='個人的なメモ', verbose_name='メモ')),
                ('exam', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorited_by', to='exams.exam', verbose_name='過去問')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to=settings.AUTH_USER_MODEL, verbose_name='ユーザー')),
            ],
            options={
                'verbose_name': 'お気に入り',
                'verbose_name_plural': 'お気に入り一覧',
                'ordering': ['-created_at'],
                'unique_together': {('user', 'exam')},
            },
        ),
    ]
