# Generated by Django 4.2 on 2026-01-27 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exam',
            name='department',
            field=models.CharField(blank=True, help_text='例: 工学部、法学部、理学部 数学科', max_length=100, verbose_name='学部・学科'),
        ),
    ]
