# Generated by Django 4.2 on 2026-01-28 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0002_exam_department'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exam',
            name='problem_url',
            field=models.URLField(blank=True, help_text='大学公式または信頼できるソースの問題PDFリンク', max_length=500, verbose_name='問題PDF URL'),
        ),
    ]
