# Generated by Django 4.2.27 on 2026-02-08 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0004_alter_exam_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answersource',
            name='has_video_explanation',
        ),
    ]
