# Generated by Django 4.2.27 on 2026-02-08 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exams', '0005_remove_answersource_has_video_explanation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='university',
            options={'ordering': ['name_kana', 'name'], 'verbose_name': '学校', 'verbose_name_plural': '学校一覧'},
        ),
        migrations.AddField(
            model_name='university',
            name='has_official_pastpaper',
            field=models.BooleanField(default=False, help_text='公式HPに過去問が掲載されているか', verbose_name='公式HP過去問掲載'),
        ),
        migrations.AddField(
            model_name='university',
            name='pastpaper_checked_at',
            field=models.DateTimeField(blank=True, help_text='過去問掲載状況を最後に確認した日時', null=True, verbose_name='確認日時'),
        ),
        migrations.AddField(
            model_name='university',
            name='pastpaper_note',
            field=models.TextField(blank=True, help_text='過去問掲載に関する備考', verbose_name='備考'),
        ),
        migrations.AddField(
            model_name='university',
            name='pastpaper_url',
            field=models.URLField(blank=True, help_text='公式サイトの過去問ページURL', verbose_name='過去問ページURL'),
        ),
        migrations.AddField(
            model_name='university',
            name='pastpaper_years',
            field=models.CharField(blank=True, help_text='例: 2025, 2024, 2023', max_length=200, verbose_name='掲載年度'),
        ),
    ]
